export const DEPARTMENTS = [
  'Amazonas',
  'Antioquia',
  'Arauca',
  'Atlántico',
  'Bolívar',
  'Boyacá',
  'Caldas',
  'Caquetá',
  'Casanare',
  'Cauca',
  'Cesar',
  'Chocó',
  'Córdoba',
  'Cundinamarca',
  'Guainía',
  'Guaviare',
  'Huila',
  'La Guajira',
  'Magdalena',
  'Meta',
  'Nariño',
  'Norte de Santander',
  'Putumayo',
  'Quindío',
  'Risaralda',
  'San Andrés y Providencia',
  'Santander',
  'Sucre',
  'Tolima',
  'Valle del Cauca',
  'Vaupés',
  'Vichada',
];

export const CITIES: Record<string, string[]> = {
  Amazonas: ['Leticia', 'Puerto Nariño'],
  Antioquia: [
    'Medellín',
    'Bello',
    'Itagüí',
    'Envigado',
    'Apartadó',
    'Rionegro',
    'Caucasia',
    'Turbo',
    'Magangué',
  ],
  Arauca: ['Arauca', 'Arauquita', 'Saravena', 'Tame'],
  Atlántico: [
    'Barranquilla',
    'Soledad',
    'Malambo',
    'Sabanalarga',
    'Baranoa',
    'Galapa',
  ],
  Bolívar: ['Cartagena', 'Magangué', 'Turbaco', 'El Carmen de Bolívar'],
  Boyacá: ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Paipa'],
  Caldas: ['Manizales', 'La Dorada', 'Chinchiná', 'Villamaría'],
  Caquetá: ['Florencia', 'San Vicente del Caguán'],
  Casanare: ['Yopal', 'Aguazul', 'Villanueva'],
  Cauca: ['Popayán', 'Santander de Quilichao', 'Puerto Tejada'],
  Cesar: ['Valledupar', 'Aguachica', 'Agustín Codazzi'],
  Chocó: ['Quibdó', 'Istmina'],
  Córdoba: ['Montería', 'Lorica', 'Sahagún', 'Cereté'],
  Cundinamarca: [
    'Bogotá',
    'Soacha',
    'Fusagasugá',
    'Facatativá',
    'Zipaquirá',
    'Chía',
    'Girardot',
    'Mosquera',
    'Madrid',
    'Funza',
    'Cajicá',
  ],
  Guainía: ['Inírida'],
  Guaviare: ['San José del Guaviare'],
  Huila: ['Neiva', 'Pitalito', 'Garzón', 'La Plata'],
  'La Guajira': ['Riohacha', 'Maicao', 'Uribia'],
  Magdalena: ['Santa Marta', 'Ciénaga', 'Zona Bananera'],
  Meta: ['Villavicencio', 'Acacías', 'Granada'],
  Nariño: ['Pasto', 'Tumaco', 'Ipiales'],
  'Norte de Santander': ['Cúcuta', 'Ocaña', 'Villa del Rosario', 'Los Patios'],
  Putumayo: ['Mocoa', 'Puerto Asís'],
  Quindío: ['Armenia', 'Calarcá', 'Montenegro', 'Quimbaya', 'La Tebaida'],
  Risaralda: ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal'],
  'San Andrés y Providencia': ['San Andrés', 'Providencia'],
  Santander: [
    'Bucaramanga',
    'Floridablanca',
    'Barrancabermeja',
    'Girón',
    'Piedecuesta',
  ],
  Sucre: ['Sincelejo', 'Corozal'],
  Tolima: ['Ibagué', 'Espinal', 'Melgar'],
  'Valle del Cauca': [
    'Cali',
    'Buenaventura',
    'Palmira',
    'Tuluá',
    'Yumbo',
    'Cartago',
    'Jamundí',
    'Buga',
  ],
  Vaupés: ['Mitú'],
  Vichada: ['Puerto Carreño'],
};
